const dares = [
  "Repeat everything the person to your right says for 30 minutes",
  "Sing everything you say",
  "Impersonate someone in the room",
  "Get down on one knee and propose to the person on your left",
  "Repeat everything the person to your right says until your next turn",
  "Repeat everything the person to your left says until your next turn",
  "Give a player, of the groups choice, a foot massage",
  "Close your eyes and send a blind text to a random person",
  "Do a headstand for one minute",
  "Eat something and then talk with your mouth full",
  "Stuff ice inside your pants",
  "Sit on the lap of a guy for 5 minutes",
  "Apply a condiment to your face.",
  "Fill your mouth with water and try singing a song",
  "Make an obscene phone call to a random number",
  "Talk with your tongue sticking out",
  "Hop everywhere you go",
  "Speak with a fake accent for 1 hour",
  "Dance like a cowboy",
  "Draw something on your face in permanent marker",
  "Soak your T-shirt in water and put them in the fridge for 20 min, and then wear it",
  "Choose a person in the group and say what annoys you about them",
  "Tell a joke until it makes everyone laugh",
  "Call a super fancy restaurant and try to make a reservation under the name of Jennifer Aniston",
  "Call a friend and pick a serious fight with them",
  "Pick up something from the trash and put it in your pocket",
  "Fill up your mouth with water and sing a song until someone from the group guesses the song",
  "Show everyone your search history for the past week",
  "Do 30 pushups",
  "Try counting backwards from 100 in multiples of three",
  "Do a downward dog pose for 60 seconds",
  "Do an impression of everyone in the room",
  "Don’t speak for half an hour",
  "Do a weird dance in front of everyone with no music",
  "Sing a song for everyone",
  "Make out with your hand",
  "Fake cry",
  "Slap yourself in the face",
  "Pretend to be a ballerina",
  "Lie down and pretend you’re a fish",
  "Do your best impression of a president",
  "Sing like no one is watching",
  "Make up a rap",
  "Speak only in rhymes",
  "Show the 23rd oldest photo on your phone",
  "Say something dirty to the person on your left",
  "Show off your orgasm face",
  "Empty out your wallet/purse and show everyone what’s inside",
  "Do your best impression of a baby being born",
  "Try to lick your elbow",
  "Do your best sexy crawl",
  "Try and make the group laugh as quickly as possible",
  "Tell everyone an embarrassing story about yourself",
  "Curse like sailor for 20 seconds straight",
  "Howl like a wolf",
  "Don't call anyone by there name",
  "No pointing",
  "Do not say the word 'Drink'",
];
