const fakeTweets = [
  'We live in hell. This is hell.',
  'All the best, Kanye.',
  'Please go back on your meds, please.',
  'Stop, just stop now.',
  'What is your platform? Can you post that please? I\'d like to know what you\'re gonna do specifically?',
  'We need someone that can deal with a pamdemic+. Not a artist with rumored history of mental breakdowns.',
  'God help us.',
  'America deserves so much better. Stop making a fool of yourself, it seems that\'s all you do.',
  'Good Luck.',
  'Just to be CLEAR: WE ARE IN ENGAGED WITH HAITI’s GOVERNMENT  to make a transformational INVESTMENT to bring  JOBS,  DEVELOPMENT, HELP SUPPORT LOCAL FARMERS and FISHERMEN and Build a new « CITY OF THE FUTURE » in a very beautiful country.',
  'You got my vote.',
  'I have a good feeling about 2021.',
  'Break up with the Democrats Black America. Can\'t you see that their policies have kept us in chains?',
  'We don’t need a clown in the WH! Stick to your music.',
  'Let me know how i can give my money to you!!!!',
  'I guess the plot of «Idiocracy» really is coming true.',
  'Anyone but a Democrat.',
  'Yes, this way a lot of black voters will vote for Kanye west and all loyal Trump supporters stick with me for another four more years.',
  'Try growing a brain!',
  'Kanye is an embarassment to all of us. He’s lost his soul. This is why Jay Z got rid of him. How can u REMAIN friends with someone like this?',
  'He\'s a smart guy and to those who say he can\'t win there are a ton of people who would vote for him and no dementia or other mental issues. I think its a win for USA.',
  'Good luck, America.',
  'This goes to show how uneducated the US has become.',
  'First order of business will be.....?',
  'See when you have money you can care less about the people.',
  'Stop. Just stop. We know you are.',
  'Whomever just unfollowed me - show yourself you coward.',
  'Protesting is unamerican. this country was founded by us hugging & kissing an oppressive regime until it died from smiling too much.',
  'Dystopian science fiction writers must be embarrassed they never thought the resistance would be park services and Teen Vogue.',
  'Oh my– Keke Palmer doesn\'t know who Dick Cheney is?',
  'Selfish, not shocked.',
  'Amy Coney Barrett uses term “originalist”  to impose her radical right wing religious views as if the Founding Fathers (49% of delegates to constitutional convention owned slaves) didn’t know how dangerous religious zealots could be. Something about separation church and state...',
  'If you are watching this and you can’t decide who to vote for, there is nothing more to say. It’s like deciding between jumping into a calm Ocean or a lava pit filled with mechanical sharks.',
  'PEOPLE TRIED TO TALK ME OUT OF RUNNING FOR PRESIDENT... NEVER LET WEAK CONTROLLING PEOPLE KILL YOUR SPIRIT.',
  'This is bad... this is very bad.',
  'I don’t wear masks like him. Every time you see him, he’s got a mask!',
  'Love your vision and your conviction. I don’t care what color you are sir, I just care that you are a red blooded American who thinks for himself.',
  'He just wants attention! That’s what celebrities do if they want to be on top of tabloids. If u believe him then u are a clown.',
  'Hopefully you can open peoples eyes to the deep state corruption. Praying you’re battling for the good side. It really is biblical!',
  'JUST SOMETHING ELSE TO DISTRACT!',
  'When God shows people a vision and confirms it with other souls, be sure it is from him. This I know because God showed this to me. I knew you would be a billionaire. You’re the smartest guy I know though some people think you’re crazy!?',
  'Somebody know what @kanyewest thinks about the climate change?',
  'This is going to be entertaining....',
  'Kanye West loves Trump.',
  'We support you and we need you. Stop racist please!',
  'Please do not do this. This is not a good idea.',
  'Beautiful. Let\'s go for a better world.',
  'I can\'t support someone like this to run our country #Trump2020',
  'So many states flipped over night. Kind of suspicious if you ask me. A recount will show that most votes we\'re invaild and shouldn\'t be counted!',
  'Sheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessssssssssh'
];
